### ISSUE TITLE
Instructions Please

### ISSUE THREAD

**Issue by ramavarma** [mellyonz/2-Week-Challenge#1]
Hi Kieran,
What do I do to get this working? No setup/configuration documents

Cheers,
Vinay

**Comment by mellyonz** [comment]
I don't know how to describe the set up very well.

1. install Apache
2. install MySQL
3. place document in htdocs

It will be the same installation as the other groups since we all used PHP.

I personally used Xampp to install all these of things. I have zero clue how do it one a Linux server or a Docker, i guess i need to know the Console commands for installation.
